import Link from 'next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ja'>
      <head />
      <body>
        <header>
          <h1 className='title'>
            <Link href="/">BKCバス時刻表</Link>
          </h1>
        </header>
        {children}
      </body>
    </html>
  )
}
